### PR TITLE
Adding setHeaders method

### PR DESCRIPTION
**Pull request by derfux**
Allows to set custom http headers via: 

```
jsonrpc.setHeaders({'X-Auth':123});
```

and/or

```
jsonrpcConfigProvider.set(headers:{'xy':123,'z':45});
```

### CODE REVIEW

**Comment by joostvunderink** [comment]
Dear Jens, thank you for your pull request. I think this is a good addition.

Could you please add unit tests for both the setting of headers via the configuration and via the request call itself? Then I can merge this.

**Comment by joostvunderink** [comment]
Actually, after thinking about it a bit more, I think it should be implemented slightly differently. These headers could be use for example for authentication. And in that case, you want to be able to send different headers to different JSON-RPC servers.

So I'll implement this, but with the `headers` option inside the `servers` argument of `jsonrpcConfig`. Or, if you want to do that, that's fine too of course.

**Comment by derfux** [comment]
He Joost, thats a good point, i have changed it in this direction.
May you can add the tests?

**Comment by joostvunderink** [comment]
Dear Jens, thanks again. I've made my own code and tests based on your pull request. So I'm closing this pull request.

Your request has been fulfilled in version 0.2.0: the `servers` argument now has a `headers` field for your custom headers. See the new example file for a working example.

I hope this helps you! And if not, let me know.

**Comment by derfux** [comment]
He Joost, actually, the idea with the setHeaders method was to have the ability to set headers at runtime. For example after a authentication token has been received.
If i see this correct, i can not inject data into the .config block later or rather it wont be recognized by the jsonrpc service at runtime.
But maybe I overlooked a different way to achieve this?

**Comment by joostvunderink** [comment]
Hm, I understand your needs. And with the current setup, I am pretty sure that what you want is impossible. Let me think a bit on how to solve that in the best way!

**Pull request closed without merging**
